spring.application.name=firebase_auth


server.port=8092

spring.datasource.url=jdbc:postgresql://localhost:5432/fireauthprac
spring.datasource.username=postgres
spring.datasource.password=Shakti
spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


firebase.web-api-key=AIzaSyCtKOG-djZ0pdOmKSd4ogtT57z4DS_PzKQ