spring.application.name=firebase_auth


server.port=8094

spring.datasource.url=jdbc:postgresql://localhost:5432/fireauthprac
spring.datasource.username=postgres
spring.datasource.password=Shakti
spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


# swagger
# Enable OpenAPI Documentation
# OpenAPI + Swagger UI
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs

springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# Let Springdoc scan all controllers
springdoc.paths-to-match=/api/**

# connection poolinmg for dtatabase optimization
# spring.datasource.hikari.pool-name=HikariCP
# spring.datasource.hikari.maximum-pool-size=100
# spring.datasource.hikari.minimum-idle=50
# spring.datasource.hikari.idle-timeout=30000
# spring.datasource.hikari.max-lifetime=1800000
# spring.datasource.hikari.connection-timeout=30000
# spring.datasource.hikari.validation-timeout=5000
# spring.datasource.hikari.leak-detection-threshold=15000

# spring.jpa.properties.hibernate.id.new_generator_mappings=true  # For faster ID generation


#In HikariCP, the spring.datasource.hikari.auto-commit=true setting determines the default
#   auto-commit behavior for database connections retrieved from the connection pool.
# spring.datasource.hikari.auto-commit=true

#to track statistics of query running
# spring.jpa.properties.hibernate.generate_statistics=true
# logging.level.org.hibernate=debug

# Cloudinaryt
cloudinary.cloud_name=ds688jnk7
cloudinary.api_key=218583382113925
cloudinary.api_secret=58Tb1t7QkA7NFVZXYDmPfGlxvzA



# Enable Multipart file uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB




spring.boot.admin.client.url=http://localhost:8087
spring.boot.admin.client.username=admin 
spring.boot.admin.client.password=adminpassword

# Actuator Configuration
management.endpoints.web.exposure.include=*
management.endpoints.web.base-path=/actuator
management.endpoint.health.show-details=always
management.endpoint.health.show-compgitonents=always

# Enable Disk Space Health Indicator (optional customization)
management.health.diskspace.enabled=true
management.health.diskspace.threshold=1000000000

# Enable Spring Boot Admin UI
spring.boot.admin.ui.enabled=true
spring.boot.admin.security.enabled=false



firebase.web-api-key=AIzaSyCtKOG-djZ0pdOmKSd4ogtT57z4DS_PzKQ